# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3bba1d571e005b519c28ae09f753e1083acb771f427af56d49e99d841070500e6fd738034266b6586bd4abe9c83d5d3fbb45c6ff3e3dc7d63fa7578ddc218b7

test:
  secret_key_base: bec042d9c8df3baf5c4c25378c2f7418e5744ceac1fbe457ba62ea84892b12f5cb95bbf610f34f19af16e1d1883ffe9a58e2085016fcfec0503cef9a04afdf8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
